### ISSUE TITLE
BUG - Row duplication introduced when History Mode is enabled 

### ISSUE THREAD

**Issue by jcbmllgn** [fivetran/dbt_salesforce_source#15]
**Are you a current Fivetran customer?** 
Yes - Jacob Mulligan, Firefly Health, head of analytics

**Describe the bug**
I turned on history mode in Fivetran for the User, UserRole, Account, and Opportunity tables, Fivetran then ran a migration on our data in Snowflake which took a few minutes. I then enabled `history_mode` using the configuration described [here](https://github.com/fivetran/dbt_salesforce_source#salesforce-history-mode). The tests on the `salesforce_source` package stared failing.

**Steps to reproduce**

Here is the exact code we have in our `dbt_project.yml` file:

```yml
vars:
  salesforce_source:
    salesforce_database: raw
    salesforce_schema: salesforce

    using_account_history_mode_active_records: true
    using_opportunity_history_mode_active_records: true
    using_user_role_history_mode_active_records: true
    using_user_history_mode_active_records: true

```

At first tests passed and we merged this into master. Today the following tests broke:

```
Completed with 3 errors and 0 warnings:

Failure in test unique_salesforce__opportunity_enhanced_opportunity_id (models/salesforce.yml)
  Got 82 results, configured to fail if != 0

  compiled SQL at target/compiled/salesforce/models/salesforce.yml/schema_test/unique_salesforce__opportunity_enhanced_opportunity_id.sql

Failure in test unique_salesforce__owner_performance_owner_id (models/salesforce.yml)
  Got 7 results, configured to fail if != 0

  compiled SQL at target/compiled/salesforce/models/salesforce.yml/schema_test/unique_salesforce__owner_performance_owner_id.sql

Failure in test unique_stg_salesforce__user_user_id (models/stg_tables.yml)
  Got 7 results, configured to fail if != 0
```

I was able to trace these issues back to the `stg_salesforce__user_tmp.sql` model which contains row duplication. The issue seems to be that a User was updated in SalesForce and when the update was copied over to Snowflake the old record did _not_ have `_fivetran_active` set to `false`, instead `_fivetran_active` was still `null`. There are now two rows in the users_tmp model for one user, here's what this Looks like in Snowflake:

<img width="1184" alt="Pasted_Image_8_29_21__1_31_PM" src="https://user-images.githubusercontent.com/1261230/131248920-8a3e0996-618b-4cc0-91e0-942bfdba9b05.png">

Because `_fivetran_active` is null for the first row, the `coalesce()` in the `stg_salesforce__user_tmp.sql` model returns _both_ records for that user..

```sql
select *
from raw.salesforce.user

where coalesce(_fivetran_active, true)
```

**Expected behavior**
I would expect to be able to turn on History Mode for the User, UserRole, Account, and Opportunity tables and turn on History Mode for those models in this package and have the package only select the most record record for each of these tables. 

**Project variables configuration**
_I shared this above._

**Package Version**

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.1

  - package: dbt-labs/segment
    version: 0.6.0

  - package: fivetran/fivetran_log
    version: 0.4.0

  - package: fivetran/salesforce_source
    version: 0.3.1

  - package: fivetran/salesforce
    version: 0.4.0

  - package: fivetran/jira
    version: 0.4.0

  - package: calogica/dbt_date
    version: 0.4.0
```

**Warehouse**

- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Please indicate the level of urgency** 
Medium urgency. This is causing production tests to fail, we rely on this package for reporting which is now slightly incorrect (miscounting by 1 opportunity) due to this issue, we can't just remove the package because we rely on it for reporting, and lastly the failing test makes all deploys of production look broken 😦 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
