### ISSUE TITLE
[Feature] Up

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_salesforce_source#35]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Revise logic to better accommodate different user setups and add documentation to readme to account to give instructions on what to do when our yml settings get overridden. 

Things to update:

1. Update src yml 

from:
```yml
  - name: order
    identifier: >
      {% if target.type == 'snowflake' %}{{ var('salesforce_order_identifier', '"ORDER"') }}
      {% else %}{{ var('salesforce_order_identifier', 'order') }}{% endif %}
```
to 
```yml
  - name: order
    identifier: >
      {% if target.type == 'snowflake' %}{{ var('salesforce_order_identifier', 'ORDER') }} 
      {%- else %}{{ var('salesforce_order_identifier', 'order') }}{% endif %} 
  # removed double quotes and add whitespace control
    quoting:
      identifier: true 
  # turned quoting of the identifier for this table on
```

2. Update our intergration_test dbt_project.yml vars 

from:
```yml
salesforce_order_identifier: "sf_order_data"
```
to
```yml
order: "{{ ref('sf_order_data') }}" 
```

3. Update README

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.
