### ISSUE TITLE
override default database and schema

### ISSUE THREAD

**Issue by mattarderne** [fivetran/dbt_salesforce_source#6]
I'm trying to configure my package with the below `vars`

```
vars:
  salesforce_source:
    salesforce_database: "RAW_PROD"
    salesforce_schema: "RW_SALESFORCE_PROD"  
```

I've added above to `dbt_modules/salesforce_source/dbt_project.yml` and ran `dbt deps` then `dbt run` and I get the below error

```
Database Error in model stg_salesforce__account_tmp (models/tmp/stg_salesforce__account_tmp.sql)
  002003 (02000): SQL compilation error:
  Schema 'ANALYTICS_DEV.SALESFORCE' does not exist or not authorized.
```

I also tried adding the vars to `/dbt_project.yml` with the same result.

Perhaps I am missing something foundational here
